AllCops:
  NewCops: enable
Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false













